<?php
/**
 * @file
 * menu_link.e20b5bfbd847678374f7c42f349ba57a13a13e8d.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'node/10',
  'link_title' => 'Дорогая редакция',
  'menu_name' => 'menu-bottom-menu',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
  ),
  'router_path' => 'node/%',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_bottom_menu' => 'menu.menu_bottom_menu',
);

$optional = array();

$modules = array();
