<?php
/**
 * @file
 * variable.imce_roles_profiles.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'imce_roles_profiles',
  'content' => array(
    200153887 => array(
      'weight' => '0',
      'public_pid' => '2',
    ),
    30037204 => array(
      'weight' => '0',
      'public_pid' => '2',
    ),
    2 => array(
      'weight' => 11,
      'public_pid' => 0,
    ),
    1 => array(
      'weight' => 12,
      'public_pid' => 0,
    ),
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
